name: Works submission
description: 补充作品信息或材料
title: "[Works]: "
labels: ["works"]
body:
  - type: input
    id: project_name
    attributes:
      label: 作品名称
    validations:
      required: true
  - type: textarea
    id: materials
    attributes:
      label: 需要补充的材料
      description: 可填写文档、代码、图片、演示视频或其他资料。
    validations:
      required: false
